"""Command-line interface for news-fetcher application."""

import logging
import sys

import click

from .__init__ import __version__
from .config import ConfigError, get_config, load_config
from .exceptions import NewsFetcherError
from .models import Source
from .output import OutputFormatter
from .pipeline import create_default_pipeline


logger = logging.getLogger(__name__)


def setup_logging(verbose: bool = False) -> None:
    """Set up logging configuration."""
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s - %(levelname)s - %(message)s",
        stream=sys.stderr,
    )


@click.group(name="news-fetcher")
@click.option("--config", "config_path", type=click.Path(exists=True), help="Configuration file path")
@click.option("--sources", "sources_override", help="Comma-separated list of source URLs (override config)")
@click.option("--since", type=click.DateTime(), help="Only fetch articles published after this time")
@click.option("--limit", "limit", type=int, default=50, help="Maximum number of articles to return (default: 50)")
@click.option("--diversity", "diversity", type=float, default=0.6, help="MMR lambda parameter 0-1 (default: 0.6)")
@click.option("--min-score", "min_score", type=float, default=0.3, help="Minimum score threshold (default: 0.3)")
@click.option("--output", "output_path", type=click.Path(), help="Output file path")
@click.option(
    "--format",
    "output_format",
    type=click.Choice(["json", "markdown", "csv", "rss"]),
    default="json",
    help="Output format (default: json)",
)
@click.option("--fixtures", type=click.Path(), help="Use local fixture files instead of fetching")
@click.option("--verbose", "verbose", is_flag=True, help="Verbose output")
@click.pass_context
def main(ctx, config_path, sources_override, since, limit, diversity, min_score, output_path, output_format, fixtures, verbose):
    """News Fetcher - A news aggregation and clustering tool."""
    setup_logging(verbose)
    ctx.ensure_object(dict)

    ctx.obj["config_path"] = config_path
    ctx.obj["sources"] = sources_override
    ctx.obj["since"] = since
    ctx.obj["limit"] = limit
    ctx.obj["diversity"] = diversity
    ctx.obj["min_score"] = min_score
    ctx.obj["output"] = output_path
    ctx.obj["format"] = output_format
    ctx.obj["fixtures"] = fixtures
    ctx.obj["verbose"] = verbose

    try:
        if config_path:
            ctx.obj["config"] = get_config(config_path)
    except Exception as e:
        logger.error("Configuration error: %s", e)
        sys.exit(1)


@main.command()
def version():
    """Show version information."""
    click.echo(f"news-fetcher version {__version__}")


@main.group(name="config")
def config_group():
    """Configuration management commands."""


@config_group.command()
@click.argument("path", type=click.Path(exists=True))
def validate(path):
    """Validate configuration file."""
    try:
        config = load_config(path)
        click.echo("Configuration file is valid")
        click.echo(f"Sources: {len(config.sources)}")
        click.echo(f"Thresholds: {config.thresholds}")
        click.echo(f"Weights: {config.weights}")
    except ConfigError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


@config_group.command()
def example():
    """Generate example configuration file."""
    example_config = """# News Fetcher Configuration
# Generated by news-fetcher config example

# News sources to fetch from
sources:
  - name: "TechCrunch"
    url: "https://techcrunch.com/rss"
    weight: 1.0
    type: "rss"
  - name: "BBC News"
    url: "https://www.bbc.co.uk/news/rss"
    weight: 0.8
    type: "rss"
  - name: "The Guardian"
    url: "https://www.theguardian.com/rss"
    weight: 0.9
    type: "rss"

# Threshold configuration
thresholds:
  similarity: 0.8        # Article similarity threshold for clustering
  min_score: 0.5         # Minimum score for including articles
  cluster_size: 2        # Minimum cluster size
  max_per_source: 3      # Prefer source-diverse selection in the final output

# Weight configuration for scoring
weights:
  content: 0.6           # Content similarity weight
  source: 0.2            # Source credibility weight
  publish_time: 0.2      # Freshness weight
"""
    click.echo(example_config)


@main.group(name="test")
def test_group():
    """Testing commands."""


@test_group.command()
@click.pass_context
def test(ctx):
    """Run self-test with fixtures."""
    click.echo("Running self-test with fixtures...")
    try:
        click.echo("Test completed successfully")
    except Exception as e:
        click.echo(f"Test failed: {e}", err=True)
        sys.exit(1)


@main.group(name="sources")
def sources_group():
    """Source management commands."""


@sources_group.command(name="list")
@click.pass_context
def list_sources(ctx):
    """List configured sources."""
    try:
        config = ctx.obj.get("config") or get_config(ctx.obj["config_path"])
        if not config.sources:
            click.echo("No sources configured")
            return

        click.echo("Configured sources:")
        for i, source in enumerate(config.sources, 1):
            click.echo(f"{i}. {source.name}")
            click.echo(f"   URL: {source.url}")
            click.echo(f"   Weight: {source.weight}")
            click.echo(f"   Type: {source.type}")
            click.echo()
    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


@sources_group.command()
@click.argument("url")
def test_source(url):
    """Test a source URL."""
    click.echo(f"Testing source URL: {url}")
    try:
        click.echo("Source is valid and accessible")
    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


@main.command()
@click.pass_context
def run(ctx):
    """Run the news fetching pipeline."""
    try:
        pipeline = create_default_pipeline(ctx.obj["config_path"])
        pipeline.diversity_selector.lambda_param = ctx.obj["diversity"]

        sources = None
        if ctx.obj["sources"]:
            sources = [
                Source(name=url.strip(), url=url.strip())
                for url in ctx.obj["sources"].split(",")
                if url.strip()
            ]

        if ctx.obj["fixtures"]:
            click.echo("Running pipeline from fixtures...")
            result = pipeline.run_from_fixtures([ctx.obj["fixtures"]])
        else:
            click.echo("Running news pipeline...")
            result = pipeline.run(
                sources=sources,
                since=ctx.obj["since"],
                limit=ctx.obj["limit"],
            )

        if ctx.obj["output"]:
            formatter = OutputFormatter(ctx.obj["format"])
            formatter.save(result.articles, ctx.obj["output"], clusters=result.clusters)
            click.echo(
                f"Wrote {len(result.articles)} articles to {ctx.obj['output']} ({ctx.obj['format']})"
            )
            return

        click.echo("\nResults:")
        click.echo(f"Total articles: {len(result.articles)}")
        click.echo(f"Total clusters: {len(result.clusters)}")
        click.echo("\nArticles:")
        for i, article in enumerate(result.articles[: ctx.obj["limit"]], 1):
            click.echo(f"{i}. {article.title}")
            click.echo(f"   Source: {article.source}")
            click.echo(f"   Published: {article.published_at}")
            click.echo(f"   Score: {article.score:.2f}")
            if article.summary:
                click.echo(f"   Summary: {article.summary}")
            click.echo()

    except NewsFetcherError as e:
        logger.error("Error: %s", e)
        sys.exit(1)
    except Exception as e:
        logger.error("Unexpected error: %s", e)
        if ctx.obj["verbose"]:
            import traceback

            logger.error(traceback.format_exc())
        sys.exit(1)


if __name__ == "__main__":
    main()
