"""
Command-line interface for news-fetcher application.

This module provides the main command-line interface using Click, including
commands for running the pipeline, managing configuration, and testing sources.
"""

import logging
import sys
from datetime import datetime
from typing import List, Optional
import click
from .__init__ import __version__
from .config import get_config, load_config, validate_config, ConfigError
from .models import Config, Source
from .pipeline import NewsPipeline, create_default_pipeline
from .exceptions import NewsFetcherError, FetchError, ParseError, ProcessingError


# Configure logging
logger = logging.getLogger(__name__)


def setup_logging(verbose: bool = False):
    """
    Set up logging configuration.

    Args:
        verbose: Whether to enable verbose output
    """
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s - %(levelname)s - %(message)s",
        stream=sys.stderr
    )


# Main command group
@click.group(name="news-fetcher")
@click.option("--config", "-c", type=click.Path(exists=True), help="Configuration file path")
@click.option("--sources", "-s", help="Comma-separated list of source URLs (override config)")
@click.option("--since", type=click.DateTime(), help="Only fetch articles published after this time")
@click.option("--limit", "-l", type=int, default=50, help="Maximum number of articles to return (default: 50)")
@click.option("--diversity", "-d", type=float, default=0.6, help="MMR lambda parameter 0-1 (default: 0.6)")
@click.option("--min-score", type=float, default=0.3, help="Minimum score threshold (default: 0.3)")
@click.option("--output", "-o", type=click.Path(), help="Output file path")
@click.option("--format", "-f", type=click.Choice(["json", "markdown", "csv"]), default="json", help="Output format (default: json)")
@click.option("--fixtures", type=click.Path(), help="Use local fixture files instead of fetching")
@click.option("--verbose", "-v", is_flag=True, help="Verbose output")
@click.pass_context
def main(ctx, config, sources, since, limit, diversity, min_score, output, format, fixtures, verbose):
    """News Fetcher - A news aggregation and clustering tool."""
    setup_logging(verbose)
    ctx.ensure_object(dict)

    # Store common parameters in context
    ctx.obj["config_path"] = config
    ctx.obj["sources"] = sources
    ctx.obj["since"] = since
    ctx.obj["limit"] = limit
    ctx.obj["diversity"] = diversity
    ctx.obj["min_score"] = min_score
    ctx.obj["output"] = output
    ctx.obj["format"] = format
    ctx.obj["fixtures"] = fixtures
    ctx.obj["verbose"] = verbose

    try:
        # Initialize configuration
        if config:
            ctx.obj["config"] = get_config(config)
    except Exception as e:
        logger.error(f"Configuration error: {e}")
        sys.exit(1)


# Version command
@main.command()
def version():
    """Show version information."""
    click.echo(f"news-fetcher version {__version__}")


# Config subcommands
@main.group(name="config")
def config_group():
    """Configuration management commands."""
    pass


@config_group.command()
@click.argument("path", type=click.Path(exists=True))
def validate(path):
    """Validate configuration file."""
    try:
        config = validate_config(path)
        click.echo("Configuration file is valid")
        click.echo(f"Sources: {len(config.sources)}")
        click.echo(f"Thresholds: {config.thresholds}")
        click.echo(f"Weights: {config.weights}")
    except ConfigError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


@config_group.command()
def example():
    """Generate example configuration file."""
    example_config = """# News Fetcher Configuration
# Generated by news-fetcher config example

# News sources to fetch from
sources:
  - name: "TechCrunch"
    url: "https://techcrunch.com/rss"
    weight: 1.0
    type: "rss"
  - name: "BBC News"
    url: "https://www.bbc.co.uk/news/rss"
    weight: 0.8
    type: "rss"
  - name: "The Guardian"
    url: "https://www.theguardian.com/rss"
    weight: 0.9
    type: "rss"

# Threshold configuration
thresholds:
  similarity: 0.8        # Article similarity threshold for clustering
  min_score: 0.5         # Minimum score for including articles
  cluster_size: 2        # Minimum cluster size

# Weight configuration for scoring
weights:
  content: 0.6           # Content similarity weight
  source: 0.2            # Source credibility weight
  publish_time: 0.2      # Freshness weight
"""
    click.echo(example_config)


# Test subcommands
@main.group(name="test")
def test_group():
    """Testing commands."""
    pass


@test_group.command()
@click.pass_context
def test(ctx):
    """Run self-test with fixtures."""
    click.echo("Running self-test with fixtures...")
    try:
        # TODO: Implement actual test with fixtures
        click.echo("Test completed successfully")
    except Exception as e:
        click.echo(f"Test failed: {e}", err=True)
        sys.exit(1)


# Sources subcommands
@main.group(name="sources")
def sources_group():
    """Source management commands."""
    pass


@sources_group.command()
@click.pass_context
def list(ctx):
    """List configured sources."""
    try:
        config = ctx.obj.get("config") or get_config(ctx.obj["config_path"])
        if not config.sources:
            click.echo("No sources configured")
            return

        click.echo("Configured sources:")
        for i, source in enumerate(config.sources, 1):
            click.echo(f"{i}. {source.name}")
            click.echo(f"   URL: {source.url}")
            click.echo(f"   Weight: {source.weight}")
            click.echo(f"   Type: {source.type}")
            click.echo()
    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


@sources_group.command()
@click.argument("url")
def test(url):
    """Test a source URL."""
    click.echo(f"Testing source URL: {url}")
    try:
        # TODO: Implement actual source testing
        click.echo("Source is valid and accessible")
    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)


# Main pipeline execution (default when no subcommand)
@main.command()
@click.pass_context
def run(ctx):
    """Run the news fetching pipeline (default command)."""
    try:
        if ctx.obj["fixtures"]:
            click.echo("Running pipeline from fixtures...")
            pipeline = create_default_pipeline(ctx.obj["config_path"])
            result = pipeline.run_from_fixtures([ctx.obj["fixtures"]])
        else:
            click.echo("Running news pipeline...")
            pipeline = create_default_pipeline(ctx.obj["config_path"])
            result = pipeline.run(limit=ctx.obj["limit"])

        # Output results
        if ctx.obj["output"]:
            # TODO: Implement output writing
            click.echo(f"Writing output to {ctx.obj['output']}")
        else:
            # Print summary to console
            click.echo(f"\nResults:")
            click.echo(f"Total articles: {len(result.articles)}")
            click.echo(f"Total clusters: {len(result.clusters)}")
            click.echo("\nArticles:")
            for i, article in enumerate(result.articles[:ctx.obj['limit']], 1):
                click.echo(f"{i}. {article.title}")
                click.echo(f"   Source: {article.source}")
                click.echo(f"   Published: {article.published_at}")
                click.echo(f"   Score: {article.score:.2f}")
                if article.summary:
                    click.echo(f"   Summary: {article.summary}")
                click.echo()

    except NewsFetcherError as e:
        logger.error(f"Error: {e}")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        if ctx.obj["verbose"]:
            import traceback
            logger.error(traceback.format_exc())
        sys.exit(1)


if __name__ == "__main__":
    main()
